import React, { useEffect, useState } from "react"
import { useLocation } from "react-router-dom"
import Button from '../../basic/Button'
import { Trash } from "@iconsans/react/linear"

const InvoiceTemplate = () => {
    const location = useLocation()
    const [invoice, setInvoice] = useState({
        invoiceId: "",
        profielPicUrl: "",
        senderName: "",
        senderEmail: "",
        senderAddress: "",
        recipientName: "",
        recipientEmail: "",
        recipientAddress: "",
        billTitle: "",
        issuedOn: "",
        dueDate: "",
        terms: "",
        tax: "",
        itemList: []
    })
    useEffect(() => {
        if (location.state) {
            setInvoice(location.state)
        }
    }, [])
    const toCurrencyFormat = (number) =>
        number.toLocaleString('en-US', { style: 'currency', currency: 'NGN' });
    const calculateTotal = () =>
        invoice.itemList.reduce((acc, item) => acc + item.itemRate * item.itemQuantity, 0);

    return (
        <>
            <div className="p-8 bg-gray-200 flex flex-col justify-center min-h-screen font-lato">
                <div className="bg-white rounded-lg flex flex-col w-full h-full p-5">

                    <div className="flex justify-between items-center flex-1">
                        <img src={invoice.profielPicUrl || 'https://via.placeholder.com/150'}
                            className="rounded-full w-32 h-32 bg-gray-300 border-2 border-black" />

                        <div className="flex flex-col text-end">
                            <h1 className="text-5xl">INVOICE</h1>
                            <p className="text-xl">INVOICE NO: <span className="text-darkPrimary"> #{invoice.invoiceId}</span></p>
                        </div>
                    </div>

                    <div className="flex flex-col flex-1 justify-start mt-8 px-4">
                        <p className="font-extrabold">Bill To:</p>
                        <p>{invoice.recipientName}</p>
                        <p>{invoice.recipientAddress}</p>
                        <p>{invoice.recipientEmail}</p>
                    </div>


                    {/* Items */}
                    <div className="flex-1 text-center mt-14">
                        <div className="grid grid-cols-4 py-2 gap-4 bg-black text-white">
                            <p>Item</p>
                            <p>Quantity</p>
                            <p>Rate</p>
                            <p>Amount</p>
                        </div>

                        <div className="grid grid-cols-4 gap-4 mt-5 place-items-center">
                            {invoice.itemList?.map((item, index) => (
                                <React.Fragment key={index}>
                                    <p className="capitalize">{item.itemName}</p>
                                    <p>{item.itemQuantity}</p>
                                    <p className="">{toCurrencyFormat(item.itemRate)}</p>
                                    <p className="">{toCurrencyFormat(item.itemRate * item.itemQuantity)}</p>
                                </React.Fragment>
                            ))}
                        </div>

                        {/* Total Row */}
                        <div className="grid grid-cols-4 mt-8 py-2 items-center border-b border-t border-black">
                            <div className="col-span-3 text-right font-bold mx-3">Total:</div>
                            <div className="col-span-1 font-bold">{toCurrencyFormat(calculateTotal())}</div>
                        </div>
                    </div>


                    <div className="flex flex-col mt-20 px-3">
                        <p className="font-bold">Title:</p>
                        <p>{invoice.billTitle}</p>
                    </div>
                    <div className="flex flex-col mt-5 px-3">
                        <p className="font-bold">Terms:</p>
                        <p>{invoice.terms}</p>
                    </div>

                    <div className="flex flex-col items-end mt-10">
                        <p className="text-2xl">{invoice.senderName}</p>
                        <p>{invoice.senderAddress}</p>
                    </div>
                </div>

                <div className="bg-black flex text-white p-3 justify-center items-center rounded-[0px_0px_8px_8px]">
                    <p>Generated by  <span className="text-darkPrimary">WEHUB INVOICE GENERATOR</span></p>
                </div>

                <div className="flex mt-3 p-5 justify-center gap-5">
                    <Button className="bg-red-500 text-white px-7 py-3 rounded-lg" defaultText={'Discard'} />
                    <Button className="bg-black text-white px-7 py-3 rounded-lg" defaultText={'Save'} />
                    <Button className="bg-darkPrimary text-white px-7 py-3 rounded-lg" defaultText={'Download to PDF'} />
                </div>

            </div>



        </>
    )
}

export default InvoiceTemplate